source "https://rubygems.org"

gem "middleman",            "~> 3.0"

gem "nokogiri"
gem "builder",              "~> 3.0"
gem "haml",                 "~> 4.0"
gem "middleman-blog",       "~> 3.2"
gem "middleman-livereload", "~> 3.0"
gem "rb-inotify",           "~> 0.9"
gem "sass",                 "~> 3.2"
gem "redcarpet", "~> 2.0"
gem "middleman-syntax"
gem "middleman-minify-html"
gem "bootstrap-sass", "~> 2.3"
gem "rake", "~> 10"
